fix bug

diff --git a/hadoop/init.d/hadoop-hdfs-httpfs b/hadoop/init.d/hadoop-hdfs-httpfs
--- a/hadoop/init.d/hadoop-hdfs-httpfs
+++ b/hadoop/init.d/hadoop-hdfs-httpfs
@@ -15,14 +15,14 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-# Starts a Hive Server2
+# Starts a Hadoop datanode
 #
-# chkconfig: 345 85 15
-# description: Hive Server2
+# chkconfig: 345 90 10 
+# description: Hadoop httpfs
 #
 ### BEGIN INIT INFO
-# Provides:          hive-server2
-# Short-Description: Hive Server2
+# Provides:          hadoop-hdfs-httpfs
+# Short-Description: Hadoop httpfs
 # Default-Start:     3 4 5
 # Default-Stop:      0 1 2 6
 # Required-Start:    $syslog $remote_fs
@@ -30,15 +30,11 @@
 # Should-Start:
 # Should-Stop:
 ### END INIT INFO
-
-service=`cat /etc/default/services | grep Hive-Server2`
+service=`cat /etc/default/services | grep Httpfs`
 if [ -z "$service" ];then
 	exit 1
 fi
 . /lib/lsb/init-functions
-BIGTOP_DEFAULTS_DIR=${BIGTOP_DEFAULTS_DIR-/etc/default}
-[ -n "${BIGTOP_DEFAULTS_DIR}" -a -r ${BIGTOP_DEFAULTS_DIR}/hadoop ] && . ${BIGTOP_DEFAULTS_DIR}/hadoop
-[ -n "${BIGTOP_DEFAULTS_DIR}" -a -r ${BIGTOP_DEFAULTS_DIR}/hive-server2 ] && . ${BIGTOP_DEFAULTS_DIR}/hive-server2
 
 # Autodetect JAVA_HOME if not defined
 . /usr/lib/bigtop-utils/bigtop-detect-javahome
@@ -60,60 +56,45 @@ RETVAL=0
 SLEEP_TIME=5
 PROC_NAME="java"
 
-DAEMON="hive-server2"
-DESC="Hive Server2"
-HIVE_HOME="/home/hadoop/hive"
-EXEC_PATH="$HIVE_HOME/bin/hive"
+DAEMON="hadoop-hdfs-httpfs"
+DESC="Hadoop httpfs"
+EXEC_PATH="$HADOOP_HOME/sbin/httpfs.sh"
 EXEC_DIR=""
 SVC_USER="hadoop"
-DAEMON_FLAGS=""
-CONF_DIR="$HIVE_HOME/conf"
-PIDFILE="/var/run/hive/hive-server2.pid"
+DAEMON_FLAGS="httpfs"
+CONF_DIR="$HADOOP_HOME/conf"
+PIDFILE="/tmp/httpfs.pid"
 LOCKDIR="/var/lock/subsys"
-LOCKFILE="$LOCKDIR/hive-server2"
-WORKING_DIR="/var/lib/hive"
+LOCKFILE="$LOCKDIR/hadoop-hdfs-httpfs"
 
-install -d -m 0755 -o hadoop -g hadoop /var/run/hive 1>/dev/null 2>&1 || :
-[ -d "$LOCKDIR" ] || install -d -m 0755 $LOCKDIR 1>/dev/null 2>&1 || :
-start() {
-    [ -x $EXE_FILE ] || exit $ERROR_PROGRAM_NOT_INSTALLED
-    log_success_msg "Starting $DESC (${DAEMON}): "
-
-    checkstatusofproc
-    status=$?
-    if [ "$status" -eq "$STATUS_RUNNING" ]; then
-        log_success_msg "${DESC} is running"
-        exit 0
-    fi
-
-    LOG_FILE=/var/log/hive/${DAEMON}.out
-
-    exec_env="HADOOP_OPTS=\"-Dhive.log.dir=`dirname $LOG_FILE` -Dhive.log.file=${DAEMON}.log -Dhive.log.threshold=INFO\""
-
-cd /data
-    su -s /bin/bash $SVC_USER -c "$exec_env nohup nice -n 0 \
-        $EXEC_PATH --service hiveserver2 $PORT \
-            > $LOG_FILE 2>&1 < /dev/null & "'echo $! '"> $PIDFILE"
-    sleep 3
-
-    checkstatusofproc
-    RETVAL=$?
-    [ $RETVAL -eq $STATUS_RUNNING ] && touch $LOCKFILE
-    return $RETVAL
+check_for_root() {
+  if [ $(id -ur) -ne 0 ]; then
+    echo 'Error: root user required'
+    echo
+    exit 1
+  fi
 }
-stop() {
-    log_success_msg "Stopping $DESC (${DAEMON}): "
-    killproc -p $PIDFILE java
-    RETVAL=$?
 
-    [ $RETVAL -eq $RETVAL_SUCCESS ] && rm -f $LOCKFILE $PIDFILE
-    return $RETVAL
+start() {
+  su -s /bin/bash hadoop -c "/home/hadoop/sbin/httpfs.sh start"
+  sleep $SLEEP_TIME
+  checkstatusofproc
+  RETVAL=$?
+
+  [ $RETVAL -eq $RETVAL_SUCCESS ] && touch $LOCKFILE
+  return $RETVAL
+}
+
+stop() {
+  su -s /bin/bash hadoop -c "/home/hadoop/sbin/httpfs.sh stop"
+  RETVAL=$?
+
+  [ $RETVAL -eq $RETVAL_SUCCESS ] && rm -f $LOCKFILE $PIDFILE
 }
 restart() {
   stop
   start
 }
-
 checkstatusofproc(){
   pidofproc -p $PIDFILE $PROC_NAME > /dev/null
 }
@@ -141,19 +122,6 @@ checkstatus(){
   esac
   return $status
 }
-
-condrestart(){
-  [ -e $LOCKFILE ] && restart || :
-}
-
-check_for_root() {
-  if [ $(id -ur) -ne 0 ]; then
-    echo 'Error: root user required'
-    echo
-    exit 1
-  fi
-}
-
 service() {
   case "$1" in
     start)
@@ -172,16 +140,10 @@ service() {
       check_for_root
       restart
       ;;
-    condrestart|try-restart)
-      check_for_root
-      condrestart
-      ;;
     *)
-      echo $"Usage: $0 {start|stop|status|restart|try-restart|condrestart}"
+      echo $"Usage: $0 {start|stop|status|restart|try-restart|condrestart|rollback}"
       exit 1
   esac
 }
 
 service "$@"
-
-exit $RETVAL
